#!/usr/bin/env.bash

# Exports
# (old)
# export FZF_DEFAULT_COMMAND='rg --files --hidden --follow --glob "!.git/*"'
# (new)
# FZF fuzzy finder for vim
# --files: List files that would be searched but do not search
# --no-ignore: Do not respect .gitignore, etc...
# --hidden: Search hidden files and folders
# --follow: Follow symlinks
# --glob: Additional conditions for search (in this case ignore everything in the .git/ folder) --glob "!.git/*"
#export FZF_DEFAULT_COMMAND='rg --files --glob "!shared-vendor/*" --glob "!*.min.js" --glob "!.git/*'


# GOLANG
export GOROOT=/usr/local/go
export GOPATH=$HOME/projects/go
export PATH=$GOPATH/bin:$GOROOT/bin:$PATH

# NVM
export NVM_DIR="$HOME/.nvm"

# Yarn
export PATH="$HOME/.yarn/bin:$HOME/.config/yarn/global/node_modules/.bin:$PATH"


# Android
export ANDROID_SDK_ROOT=$HOME/Android/Sdk

# Scripts
export PATH=$HOME/bin:$HOME/scripts:$HOME/bin/nvim:$PATH
export PATH=$HOME/.local/bin:$PATH

# NVIM mason packages
export PATH=$HOME/.local/share/nvim/mason/bin:$PATH

# Last Pass - Clipboard settings
export LPASS_CLIPBOARD_COMMAND="xclip -selection clipboard -in -l 1"

# Default editor
export EDITOR=lvim
export VISUAL=lvim

# pnpm
export PNPM_HOME="$HOME/.local/share/pnpm"
case ":$PATH:" in
  *":$PNPM_HOME:"*) ;;
  *) export PATH="$PNPM_HOME:$PATH" ;;
esac

# bun
export BUN_INSTALL="$HOME/.bun"
export PATH=$BUN_INSTALL/bin:$PATH

# composer
export COMPOSER_INSTALL="$HOME/.config/composer"
export PATH=$COMPOSER_INSTALL/vendor/bin:$PATH

# Deno
export DENO_INSTALL="$HOME/.deno"
export PATH="$DENO_INSTALL/bin:$PATH"
